<!-- 10-asynchronous/09-async-handling-errors/index.html - 10.9: gestion d'erreur (async/await) -->
<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="UTF-8" />
        <title>BeCode/JavaScript - 10.9: gestion d'erreur (async/await)</title>

        <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet" />
        <link rel="stylesheet" href="../../_shared/css/normalize.css" />
        <link rel="stylesheet" href="../../_shared/css/styles.css" />
    </head>
    <body>
        <section class="container">
            <header>
                <h1>BeCode / JavaScript</h1>
                <h2>
                    <span>10.9</span>
                    <strong>gestion d'erreur (async/await)</strong>
                </h2>
            </header>
            <main class="content">
                <article class="explain">
                    <p>La fonction <strong>window.lib.getPersons()</strong> est disponible dans le script. Elle retourn une Promise qui sera résolue, après un petit délai, avec un tableau de personnes.</p>
                    <p>Au clic sur le bouton, appelle la fonction getPersons et affiche le resultat obtenus dans la console. <strong>Attention :</strong> la Promise retournée par la fonction getPersons a plus ou moins une chance sur deux d'être rejetée avec une erreur. Si c'est le cas, utilise <em>console.error()</em> pour l'afficher.</p>
                    <p>
                        <strong>Note :</strong> pour cet exercice, utilise la syntaxe <em>async/await</em>.
                    </p>
                </article>
                <section class="material">
                    <div class="actions">
                        <button type="button" id="run">Lancer le script</button>
                    </div>
                </section>
            </main>
        </section>

        <script src="../../_shared/lib/utils.js"></script>
        <script src="../../_shared/lib/promises.js"></script>
        <script src="./script.js"></script>
    </body>
</html>

